import * as fs from 'fs-extra';
import * as path from 'path';
import { buildPluginFiles } from '../../scripts/generate-plugin';

const repoRoot = path.join(__dirname, '..', '..');
const pluginDir = path.join(repoRoot, 'plugin');

/**
 * Drift guard: the checked-in plugin/ package and marketplace manifest must
 * match what `npm run generate:plugin` produces from the current sources.
 * If any of these fail, re-run `npm run generate:plugin` and commit.
 */
describe('Claude Code plugin package', () => {
  const files = buildPluginFiles();

  it('plugin.json matches the generator output and package.json version', async () => {
    const onDisk = await fs.readJson(path.join(pluginDir, '.claude-plugin', 'plugin.json'));
    expect(onDisk).toEqual(files.pluginManifest);

    const pkg = await fs.readJson(path.join(repoRoot, 'package.json'));
    expect(onDisk.version).toBe(pkg.version);
  });

  it('marketplace.json matches the generator output and points at ./plugin', async () => {
    const onDisk = await fs.readJson(path.join(repoRoot, '.claude-plugin', 'marketplace.json'));
    expect(onDisk).toEqual(files.marketplaceManifest);
    expect(onDisk.plugins[0].source).toBe('./plugin');
    expect(onDisk.plugins[0].name).toBe('claude-task');
  });

  it('bundled command matches the content generated by init', async () => {
    const onDisk = await fs.readFile(path.join(pluginDir, 'commands', 'task.md'), 'utf8');
    expect(onDisk).toBe(files.commandContent);
  });

  it('bundled skill matches the content generated by init', async () => {
    const onDisk = await fs.readFile(path.join(pluginDir, 'skills', 'task', 'SKILL.md'), 'utf8');
    expect(onDisk).toBe(files.skillContent);
  });

  it('hooks.json matches the generator output and carries the shared SessionStart command', async () => {
    const onDisk = await fs.readJson(path.join(pluginDir, 'hooks', 'hooks.json'));
    expect(onDisk).toEqual(files.hooksConfig);
    expect(onDisk.hooks.SessionStart[0].hooks[0]).toEqual({
      type: 'command',
      command: 'claude-task status'
    });
  });

  it('.mcp.json matches the generator output and launches the MCP server via npx', async () => {
    const onDisk = await fs.readJson(path.join(pluginDir, '.mcp.json'));
    expect(onDisk).toEqual(files.mcpConfig);

    const server = onDisk.mcpServers['claude-task'];
    expect(server.command).toBe('npx');
    expect(server.args).toContain('@gonzui/claude-task-manager');
    expect(server.args).toContain('claude-task-mcp');
    expect(server.cwd).toBe('${CLAUDE_PROJECT_DIR}');
  });
});
